package exceptionHandle;

public class Exceprion2 {

	public static void main(String[] args) {
		int [] a = new int[4];   // 0 1 2 3
		a[4] = 10;   // 4 ?
		
		for (int i=0; i<4; i++) {
			System.out.println(a[i]);
		}
		try {
			
			
		} 
		
		catch (ArithmeticException e1) {  
		
			System.out.println("Exception : "+e1);
		} 
		
		catch (ArrayIndexOutOfBoundsException e2) {
			
			System.out.println("ArrayIndexOut. : "+e2);
			
		} 
		
		catch (Exception e) {   // playing safe
			
			System.out.println("Exception : "+e);
		}
		
		finally {  // for working rest of the lines
		
			System.out.println("Shanto");
		}
		
		System.out.println(".....END.....");

	}

}
